PORTNAME=	sunxi-tools
PORTVERSION=	20160606
CATEGORIES=	sysutils
PKGORIGIN=	local/${PORTDIRNAME}    # workaround for no local category

USE_GITHUB=	yes
GH_ACCOUNT=	linux-sunxi
GH_TAGNAME=	89dac0f

MAINTAINER=	ports@FreeBSD.org
COMMENT?=	tools to help hacking Allwinner A10 devices

LICENSE=	GPLv2+

USES+=		gmake

PATCH_STRIP=	-p1

.include <bsd.port.mk>
