
PKGORIGIN=	local/${PORTDIRNAME}    # workaround for no local category

MAINTAINER=	ports@FreeBSD.org
MASTERDIR=	${.CURDIR}/../../sysutils/u-boot-master

MODEL=		orangepi-pc
BOARD_CONFIG=	orangepi_pc_defconfig
FAMILY=		allwinner

.include "${MASTERDIR}/Makefile"
